name: Android Testing ARMv7

on:
  workflow_dispatch:

jobs:
  buildAndroidTesting:
    name: Build Android Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Android Testing APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          androidExportType: androidPackage

      - name: Upload Testing APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidTestingBuild
          path: build